// useHeroIcons.js
import {
    AcademicCapIcon,
    AdjustmentsHorizontalIcon,
    AdjustmentsVerticalIcon,
    ArchiveBoxArrowDownIcon,
    ArchiveBoxXMarkIcon,
    ArchiveBoxIcon,
    ArrowDownCircleIcon,
    ArrowDownLeftIcon,
    ArrowDownOnSquareStackIcon,
    ArrowDownOnSquareIcon,
    ArrowDownRightIcon,
    ArrowDownTrayIcon,
    ArrowDownIcon,
    ArrowLeftCircleIcon,
    ArrowLeftEndOnRectangleIcon,
    ArrowLeftOnRectangleIcon,
    ArrowLeftStartOnRectangleIcon,
    ArrowLeftIcon,
    ArrowLongDownIcon,
    ArrowLongLeftIcon,
    ArrowLongRightIcon,
    ArrowLongUpIcon,
    ArrowPathRoundedSquareIcon,
    ArrowPathIcon,
    ArrowRightCircleIcon,
    ArrowRightEndOnRectangleIcon,
    ArrowRightOnRectangleIcon,
    ArrowRightStartOnRectangleIcon,
    ArrowRightIcon,
    ArrowSmallDownIcon,
    ArrowSmallLeftIcon,
    ArrowSmallRightIcon,
    ArrowSmallUpIcon,
    ArrowTopRightOnSquareIcon,
    ArrowTrendingDownIcon,
    ArrowTrendingUpIcon,
    ArrowTurnDownLeftIcon,
    ArrowTurnDownRightIcon,
    ArrowTurnLeftDownIcon,
    ArrowTurnLeftUpIcon,
    ArrowTurnRightDownIcon,
    ArrowTurnRightUpIcon,
    ArrowTurnUpLeftIcon,
    ArrowTurnUpRightIcon,
    ArrowUpCircleIcon,
    ArrowUpLeftIcon,
    ArrowUpOnSquareStackIcon,
    ArrowUpOnSquareIcon,
    ArrowUpRightIcon,
    ArrowUpTrayIcon,
    ArrowUpIcon,
    ArrowUturnDownIcon,
    ArrowUturnLeftIcon,
    ArrowUturnRightIcon,
    ArrowUturnUpIcon,
    ArrowsPointingInIcon,
    ArrowsPointingOutIcon,
    ArrowsRightLeftIcon,
    ArrowsUpDownIcon,
    AtSymbolIcon,
    BackspaceIcon,
    BackwardIcon,
    BanknotesIcon,
    Bars2Icon,
    Bars3BottomLeftIcon,
    Bars3BottomRightIcon,
    Bars3CenterLeftIcon,
    Bars3Icon,
    Bars4Icon,
    BarsArrowDownIcon,
    BarsArrowUpIcon,
    Battery0Icon,
    Battery100Icon,
    Battery50Icon,
    BeakerIcon,
    BellAlertIcon,
    BellSlashIcon,
    BellSnoozeIcon,
    BellIcon,
    BoldIcon,
    BoltSlashIcon,
    BoltIcon,
    BookOpenIcon,
    BookmarkSlashIcon,
    BookmarkSquareIcon,
    BookmarkIcon,
    BriefcaseIcon,
    BugAntIcon,
    BuildingLibraryIcon,
    BuildingOffice2Icon,
    BuildingOfficeIcon,
    BuildingStorefrontIcon,
    CakeIcon,
    CalculatorIcon,
    CalendarDateRangeIcon,
    CalendarDaysIcon,
    CalendarIcon,
    CameraIcon,
    ChartBarSquareIcon,
    ChartBarIcon,
    ChartPieIcon,
    ChatBubbleBottomCenterTextIcon,
    ChatBubbleBottomCenterIcon,
    ChatBubbleLeftEllipsisIcon,
    ChatBubbleLeftRightIcon,
    ChatBubbleLeftIcon,
    ChatBubbleOvalLeftEllipsisIcon,
    ChatBubbleOvalLeftIcon,
    CheckBadgeIcon,
    CheckCircleIcon,
    CheckIcon,
    ChevronDoubleDownIcon,
    ChevronDoubleLeftIcon,
    ChevronDoubleRightIcon,
    ChevronDoubleUpIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronUpDownIcon,
    ChevronUpIcon,
    CircleStackIcon,
    ClipboardDocumentCheckIcon,
    ClipboardDocumentListIcon,
    ClipboardDocumentIcon,
    ClipboardIcon,
    ClockIcon,
    CloudArrowDownIcon,
    CloudArrowUpIcon,
    CloudIcon,
    CodeBracketSquareIcon,
    CodeBracketIcon,
    Cog6ToothIcon,
    Cog8ToothIcon,
    CogIcon,
    CommandLineIcon,
    ComputerDesktopIcon,
    CpuChipIcon,
    CreditCardIcon,
    CubeTransparentIcon,
    CubeIcon,
    CurrencyBangladeshiIcon,
    CurrencyDollarIcon,
    CurrencyEuroIcon,
    CurrencyPoundIcon,
    CurrencyRupeeIcon,
    CurrencyYenIcon,
    CursorArrowRaysIcon,
    CursorArrowRippleIcon,
    DevicePhoneMobileIcon,
    DeviceTabletIcon,
    DivideIcon,
    DocumentArrowDownIcon,
    DocumentArrowUpIcon,
    DocumentChartBarIcon,
    DocumentCheckIcon,
    DocumentCurrencyBangladeshiIcon,
    DocumentCurrencyDollarIcon,
    DocumentCurrencyEuroIcon,
    DocumentCurrencyPoundIcon,
    DocumentCurrencyRupeeIcon,
    DocumentCurrencyYenIcon,
    DocumentDuplicateIcon,
    DocumentMagnifyingGlassIcon,
    DocumentMinusIcon,
    DocumentPlusIcon,
    DocumentTextIcon,
    DocumentIcon,
    EllipsisHorizontalCircleIcon,
    EllipsisHorizontalIcon,
    EllipsisVerticalIcon,
    EnvelopeOpenIcon,
    EnvelopeIcon,
    EqualsIcon,
    ExclamationCircleIcon,
    ExclamationTriangleIcon,
    EyeDropperIcon,
    EyeSlashIcon,
    EyeIcon,
    FaceFrownIcon,
    FaceSmileIcon,
    FilmIcon,
    FingerPrintIcon,
    FireIcon,
    FlagIcon,
    FolderArrowDownIcon,
    FolderMinusIcon,
    FolderOpenIcon,
    FolderPlusIcon,
    FolderIcon,
    ForwardIcon,
    FunnelIcon,
    GifIcon,
    GiftTopIcon,
    GiftIcon,
    GlobeAltIcon,
    GlobeAmericasIcon,
    GlobeAsiaAustraliaIcon,
    GlobeEuropeAfricaIcon,
    H1Icon,
    H2Icon,
    H3Icon,
    HandRaisedIcon,
    HandThumbDownIcon,
    HandThumbUpIcon,
    HashtagIcon,
    HeartIcon,
    HomeModernIcon,
    HomeIcon,
    IdentificationIcon,
    InboxArrowDownIcon,
    InboxStackIcon,
    InboxIcon,
    InformationCircleIcon,
    ItalicIcon,
    KeyIcon,
    LanguageIcon,
    LifebuoyIcon,
    LightBulbIcon,
    LinkSlashIcon,
    LinkIcon,
    ListBulletIcon,
    LockClosedIcon,
    LockOpenIcon,
    MagnifyingGlassCircleIcon,
    MagnifyingGlassMinusIcon,
    MagnifyingGlassPlusIcon,
    MagnifyingGlassIcon,
    MapPinIcon,
    MapIcon,
    MegaphoneIcon,
    MicrophoneIcon,
    MinusCircleIcon,
    MinusSmallIcon,
    MinusIcon,
    MoonIcon,
    MusicalNoteIcon,
    NewspaperIcon,
    NoSymbolIcon,
    NumberedListIcon,
    PaintBrushIcon,
    PaperAirplaneIcon,
    PaperClipIcon,
    PauseCircleIcon,
    PauseIcon,
    PencilSquareIcon,
    PencilIcon,
    PercentBadgeIcon,
    PhoneArrowDownLeftIcon,
    PhoneArrowUpRightIcon,
    PhoneXMarkIcon,
    PhoneIcon,
    PhotoIcon,
    PlayCircleIcon,
    PlayPauseIcon,
    PlayIcon,
    PlusCircleIcon,
    PlusSmallIcon,
    PlusIcon,
    PowerIcon,
    PresentationChartBarIcon,
    PresentationChartLineIcon,
    PrinterIcon,
    PuzzlePieceIcon,
    QrCodeIcon,
    QuestionMarkCircleIcon,
    QueueListIcon,
    RadioIcon,
    ReceiptPercentIcon,
    ReceiptRefundIcon,
    RectangleGroupIcon,
    RectangleStackIcon,
    RocketLaunchIcon,
    RssIcon,
    ScaleIcon,
    ScissorsIcon,
    ServerStackIcon,
    ServerIcon,
    ShareIcon,
    ShieldCheckIcon,
    ShieldExclamationIcon,
    ShoppingBagIcon,
    ShoppingCartIcon,
    SignalSlashIcon,
    SignalIcon,
    SlashIcon,
    SparklesIcon,
    SpeakerWaveIcon,
    SpeakerXMarkIcon,
    Square2StackIcon,
    Square3Stack3DIcon,
    Squares2X2Icon,
    SquaresPlusIcon,
    StarIcon,
    StopCircleIcon,
    StopIcon,
    StrikethroughIcon,
    SunIcon,
    SwatchIcon,
    TableCellsIcon,
    TagIcon,
    TicketIcon,
    TrashIcon,
    TrophyIcon,
    TruckIcon,
    TvIcon,
    UnderlineIcon,
    UserCircleIcon,
    UserGroupIcon,
    UserMinusIcon,
    UserPlusIcon,
    UserIcon,
    UsersIcon,
    VariableIcon,
    VideoCameraSlashIcon,
    VideoCameraIcon,
    ViewColumnsIcon,
    ViewfinderCircleIcon,
    WalletIcon,
    WifiIcon,
    WindowIcon,
    WrenchScrewdriverIcon,
    WrenchIcon,
    XCircleIcon,
    XMarkIcon
  } from '@heroicons/vue/24/outline'
  
  /**
   * A mapping of kebab-case icon names to their respective Heroicon components
   */
  export const HeroOutlineIconsMap = {
    'academic-cap': AcademicCapIcon,
    'adjustments-horizontal': AdjustmentsHorizontalIcon,
    'adjustments-vertical': AdjustmentsVerticalIcon,
    'archive-box-arrow-down': ArchiveBoxArrowDownIcon,
    'archive-box-x-mark': ArchiveBoxXMarkIcon,
    'archive-box': ArchiveBoxIcon,
    'arrow-down-circle': ArrowDownCircleIcon,
    'arrow-down-left': ArrowDownLeftIcon,
    'arrow-down-on-square-stack': ArrowDownOnSquareStackIcon,
    'arrow-down-on-square': ArrowDownOnSquareIcon,
    'arrow-down-right': ArrowDownRightIcon,
    'arrow-down-tray': ArrowDownTrayIcon,
    'arrow-down': ArrowDownIcon,
    'arrow-left-circle': ArrowLeftCircleIcon,
    'arrow-left-end-on-rectangle': ArrowLeftEndOnRectangleIcon,
    'arrow-left-on-rectangle': ArrowLeftOnRectangleIcon,
    'arrow-left-start-on-rectangle': ArrowLeftStartOnRectangleIcon,
    'arrow-left': ArrowLeftIcon,
    'arrow-long-down': ArrowLongDownIcon,
    'arrow-long-left': ArrowLongLeftIcon,
    'arrow-long-right': ArrowLongRightIcon,
    'arrow-long-up': ArrowLongUpIcon,
    'arrow-path-rounded-square': ArrowPathRoundedSquareIcon,
    'arrow-path': ArrowPathIcon,
    'arrow-right-circle': ArrowRightCircleIcon,
    'arrow-right-end-on-rectangle': ArrowRightEndOnRectangleIcon,
    'arrow-right-on-rectangle': ArrowRightOnRectangleIcon,
    'arrow-right-start-on-rectangle': ArrowRightStartOnRectangleIcon,
    'arrow-right': ArrowRightIcon,
    'arrow-small-down': ArrowSmallDownIcon,
    'arrow-small-left': ArrowSmallLeftIcon,
    'arrow-small-right': ArrowSmallRightIcon,
    'arrow-small-up': ArrowSmallUpIcon,
    'arrow-top-right-on-square': ArrowTopRightOnSquareIcon,
    'arrow-trending-down': ArrowTrendingDownIcon,
    'arrow-trending-up': ArrowTrendingUpIcon,
    'arrow-turn-down-left': ArrowTurnDownLeftIcon,
    'arrow-turn-down-right': ArrowTurnDownRightIcon,
    'arrow-turn-left-down': ArrowTurnLeftDownIcon,
    'arrow-turn-left-up': ArrowTurnLeftUpIcon,
    'arrow-turn-right-down': ArrowTurnRightDownIcon,
    'arrow-turn-right-up': ArrowTurnRightUpIcon,
    'arrow-turn-up-left': ArrowTurnUpLeftIcon,
    'arrow-turn-up-right': ArrowTurnUpRightIcon,
    'arrow-up-circle': ArrowUpCircleIcon,
    'arrow-up-left': ArrowUpLeftIcon,
    'arrow-up-on-square-stack': ArrowUpOnSquareStackIcon,
    'arrow-up-on-square': ArrowUpOnSquareIcon,
    'arrow-up-right': ArrowUpRightIcon,
    'arrow-up-tray': ArrowUpTrayIcon,
    'arrow-up': ArrowUpIcon,
    'arrow-uturn-down': ArrowUturnDownIcon,
    'arrow-uturn-left': ArrowUturnLeftIcon,
    'arrow-uturn-right': ArrowUturnRightIcon,
    'arrow-uturn-up': ArrowUturnUpIcon,
    'arrows-pointing-in': ArrowsPointingInIcon,
    'arrows-pointing-out': ArrowsPointingOutIcon,
    'arrows-right-left': ArrowsRightLeftIcon,
    'arrows-up-down': ArrowsUpDownIcon,
    'at-symbol': AtSymbolIcon,
    'backspace': BackspaceIcon,
    'backward': BackwardIcon,
    'banknotes': BanknotesIcon,
    'bars-2': Bars2Icon,
    'bars-3-bottom-left': Bars3BottomLeftIcon,
    'bars-3-bottom-right': Bars3BottomRightIcon,
    'bars-3-center-left': Bars3CenterLeftIcon,
    'bars-3': Bars3Icon,
    'bars-4': Bars4Icon,
    'bars-arrow-down': BarsArrowDownIcon,
    'bars-arrow-up': BarsArrowUpIcon,
    'battery-0': Battery0Icon,
    'battery-100': Battery100Icon,
    'battery-50': Battery50Icon,
    'beaker': BeakerIcon,
    'bell-alert': BellAlertIcon,
    'bell-slash': BellSlashIcon,
    'bell-snooze': BellSnoozeIcon,
    'bell': BellIcon,
    'bold': BoldIcon,
    'bolt-slash': BoltSlashIcon,
    'bolt': BoltIcon,
    'book-open': BookOpenIcon,
    'bookmark-slash': BookmarkSlashIcon,
    'bookmark-square': BookmarkSquareIcon,
    'bookmark': BookmarkIcon,
    'briefcase': BriefcaseIcon,
    'bug-ant': BugAntIcon,
    'building-library': BuildingLibraryIcon,
    'building-office-2': BuildingOffice2Icon,
    'building-office': BuildingOfficeIcon,
    'building-storefront': BuildingStorefrontIcon,
    'cake': CakeIcon,
    'calculator': CalculatorIcon,
    'calendar-date-range': CalendarDateRangeIcon,
    'calendar-days': CalendarDaysIcon,
    'calendar': CalendarIcon,
    'camera': CameraIcon,
    'chart-bar-square': ChartBarSquareIcon,
    'chart-bar': ChartBarIcon,
    'chart-pie': ChartPieIcon,
    'chat-bubble-bottom-center-text': ChatBubbleBottomCenterTextIcon,
    'chat-bubble-bottom-center': ChatBubbleBottomCenterIcon,
    'chat-bubble-left-ellipsis': ChatBubbleLeftEllipsisIcon,
    'chat-bubble-left-right': ChatBubbleLeftRightIcon,
    'chat-bubble-left': ChatBubbleLeftIcon,
    'chat-bubble-oval-left-ellipsis': ChatBubbleOvalLeftEllipsisIcon,
    'chat-bubble-oval-left': ChatBubbleOvalLeftIcon,
    'check-badge': CheckBadgeIcon,
    'check-circle': CheckCircleIcon,
    'check': CheckIcon,
    'chevron-double-down': ChevronDoubleDownIcon,
    'chevron-double-left': ChevronDoubleLeftIcon,
    'chevron-double-right': ChevronDoubleRightIcon,
    'chevron-double-up': ChevronDoubleUpIcon,
    'chevron-down': ChevronDownIcon,
    'chevron-left': ChevronLeftIcon,
    'chevron-right': ChevronRightIcon,
    'chevron-up-down': ChevronUpDownIcon,
    'chevron-up': ChevronUpIcon,
    'circle-stack': CircleStackIcon,
    'clipboard-document-check': ClipboardDocumentCheckIcon,
    'clipboard-document-list': ClipboardDocumentListIcon,
    'clipboard-document': ClipboardDocumentIcon,
    'clipboard': ClipboardIcon,
    'clock': ClockIcon,
    'cloud-arrow-down': CloudArrowDownIcon,
    'cloud-arrow-up': CloudArrowUpIcon,
    'cloud': CloudIcon,
    'code-bracket-square': CodeBracketSquareIcon,
    'code-bracket': CodeBracketIcon,
    'cog-6-tooth': Cog6ToothIcon,
    'cog-8-tooth': Cog8ToothIcon,
    'cog': CogIcon,
    'command-line': CommandLineIcon,
    'computer-desktop': ComputerDesktopIcon,
    'cpu-chip': CpuChipIcon,
    'credit-card': CreditCardIcon,
    'cube-transparent': CubeTransparentIcon,
    'cube': CubeIcon,
    'currency-bangladeshi': CurrencyBangladeshiIcon,
    'currency-dollar': CurrencyDollarIcon,
    'currency-euro': CurrencyEuroIcon,
    'currency-pound': CurrencyPoundIcon,
    'currency-rupee': CurrencyRupeeIcon,
    'currency-yen': CurrencyYenIcon,
    'cursor-arrow-rays': CursorArrowRaysIcon,
    'cursor-arrow-ripple': CursorArrowRippleIcon,
    'device-phone-mobile': DevicePhoneMobileIcon,
    'device-tablet': DeviceTabletIcon,
    'divide': DivideIcon,
    'document-arrow-down': DocumentArrowDownIcon,
    'document-arrow-up': DocumentArrowUpIcon,
    'document-chart-bar': DocumentChartBarIcon,
    'document-check': DocumentCheckIcon,
    'document-currency-bangladeshi': DocumentCurrencyBangladeshiIcon,
    'document-currency-dollar': DocumentCurrencyDollarIcon,
    'document-currency-euro': DocumentCurrencyEuroIcon,
    'document-currency-pound': DocumentCurrencyPoundIcon,
    'document-currency-rupee': DocumentCurrencyRupeeIcon,
    'document-currency-yen': DocumentCurrencyYenIcon,
    'document-duplicate': DocumentDuplicateIcon,
    'document-magnifying-glass': DocumentMagnifyingGlassIcon,
    'document-minus': DocumentMinusIcon,
    'document-plus': DocumentPlusIcon,
    'document-text': DocumentTextIcon,
    'document': DocumentIcon,
    'ellipsis-horizontal-circle': EllipsisHorizontalCircleIcon,
    'ellipsis-horizontal': EllipsisHorizontalIcon,
    'ellipsis-vertical': EllipsisVerticalIcon,
    'envelope-open': EnvelopeOpenIcon,
    'envelope': EnvelopeIcon,
    'equals': EqualsIcon,
    'exclamation-circle': ExclamationCircleIcon,
    'exclamation-triangle': ExclamationTriangleIcon,
    'eye-dropper': EyeDropperIcon,
    'eye-slash': EyeSlashIcon,
    'eye': EyeIcon,
    'face-frown': FaceFrownIcon,
    'face-smile': FaceSmileIcon,
    'film': FilmIcon,
    'finger-print': FingerPrintIcon,
    'fire': FireIcon,
    'flag': FlagIcon,
    'folder-arrow-down': FolderArrowDownIcon,
    'folder-minus': FolderMinusIcon,
    'folder-open': FolderOpenIcon,
    'folder-plus': FolderPlusIcon,
    'folder': FolderIcon,
    'forward': ForwardIcon,
    'funnel': FunnelIcon,
    'gif': GifIcon,
    'gift-top': GiftTopIcon,
    'gift': GiftIcon,
    'globe-alt': GlobeAltIcon,
    'globe-americas': GlobeAmericasIcon,
    'globe-asia-australia': GlobeAsiaAustraliaIcon,
    'globe-europe-africa': GlobeEuropeAfricaIcon,
    'h1': H1Icon,
    'h2': H2Icon,
    'h3': H3Icon,
    'hand-raised': HandRaisedIcon,
    'hand-thumb-down': HandThumbDownIcon,
    'hand-thumb-up': HandThumbUpIcon,
    'hashtag': HashtagIcon,
    'heart': HeartIcon,
    'home-modern': HomeModernIcon,
    'home': HomeIcon,
    'identification': IdentificationIcon,
    'inbox-arrow-down': InboxArrowDownIcon,
    'inbox-stack': InboxStackIcon,
    'inbox': InboxIcon,
    'information-circle': InformationCircleIcon,
    'italic': ItalicIcon,
    'key': KeyIcon,
    'language': LanguageIcon,
    'lifebuoy': LifebuoyIcon,
    'light-bulb': LightBulbIcon,
    'link-slash': LinkSlashIcon,
    'link': LinkIcon,
    'list-bullet': ListBulletIcon,
    'lock-closed': LockClosedIcon,
    'lock-open': LockOpenIcon,
    'magnifying-glass-circle': MagnifyingGlassCircleIcon,
    'magnifying-glass-minus': MagnifyingGlassMinusIcon,
    'magnifying-glass-plus': MagnifyingGlassPlusIcon,
    'magnifying-glass': MagnifyingGlassIcon,
    'map-pin': MapPinIcon,
    'map': MapIcon,
    'megaphone': MegaphoneIcon,
    'microphone': MicrophoneIcon,
    'minus-circle': MinusCircleIcon,
    'minus-small': MinusSmallIcon,
    'minus': MinusIcon,
    'moon': MoonIcon,
    'musical-note': MusicalNoteIcon,
    'newspaper': NewspaperIcon,
    'no-symbol': NoSymbolIcon,
    'numbered-list': NumberedListIcon,
    'paint-brush': PaintBrushIcon,
    'paper-airplane': PaperAirplaneIcon,
    'paper-clip': PaperClipIcon,
    'pause-circle': PauseCircleIcon,
    'pause': PauseIcon,
    'pencil-square': PencilSquareIcon,
    'pencil': PencilIcon,
    'percent-badge': PercentBadgeIcon,
    'phone-arrow-down-left': PhoneArrowDownLeftIcon,
    'phone-arrow-up-right': PhoneArrowUpRightIcon,
    'phone-x-mark': PhoneXMarkIcon,
    'phone': PhoneIcon,
    'photo': PhotoIcon,
    'play-circle': PlayCircleIcon,
    'play-pause': PlayPauseIcon,
    'play': PlayIcon,
    'plus-circle': PlusCircleIcon,
    'plus-small': PlusSmallIcon,
    'plus': PlusIcon,
    'power': PowerIcon,
    'presentation-chart-bar': PresentationChartBarIcon,
    'presentation-chart-line': PresentationChartLineIcon,
    'printer': PrinterIcon,
    'puzzle-piece': PuzzlePieceIcon,
    'qr-code': QrCodeIcon,
    'question-mark-circle': QuestionMarkCircleIcon,
    'queue-list': QueueListIcon,
    'radio': RadioIcon,
    'receipt-percent': ReceiptPercentIcon,
    'receipt-refund': ReceiptRefundIcon,
    'rectangle-group': RectangleGroupIcon,
    'rectangle-stack': RectangleStackIcon,
    'rocket-launch': RocketLaunchIcon,
    'rss': RssIcon,
    'scale': ScaleIcon,
    'scissors': ScissorsIcon,
    'server-stack': ServerStackIcon,
    'server': ServerIcon,
    'share': ShareIcon,
    'shield-check': ShieldCheckIcon,
    'shield-exclamation': ShieldExclamationIcon,
    'shopping-bag': ShoppingBagIcon,
    'shopping-cart': ShoppingCartIcon,
    'signal-slash': SignalSlashIcon,
    'signal': SignalIcon,
    'slash': SlashIcon,
    'sparkles': SparklesIcon,
    'speaker-wave': SpeakerWaveIcon,
    'speaker-x-mark': SpeakerXMarkIcon,
    'square-2-stack': Square2StackIcon,
    'square-3-stack-3d': Square3Stack3DIcon,
    'squares-2x2': Squares2X2Icon,
    'squares-plus': SquaresPlusIcon,
    'star': StarIcon,
    'stop-circle': StopCircleIcon,
    'stop': StopIcon,
    'strikethrough': StrikethroughIcon,
    'sun': SunIcon,
    'swatch': SwatchIcon,
    'table-cells': TableCellsIcon,
    'tag': TagIcon,
    'ticket': TicketIcon,
    'trash': TrashIcon,
    'trophy': TrophyIcon,
    'truck': TruckIcon,
    'tv': TvIcon,
    'underline': UnderlineIcon,
    'user-circle': UserCircleIcon,
    'user-group': UserGroupIcon,
    'user-minus': UserMinusIcon,
    'user-plus': UserPlusIcon,
    'user': UserIcon,
    'users': UsersIcon,
    'variable': VariableIcon,
    'video-camera-slash': VideoCameraSlashIcon,
    'video-camera': VideoCameraIcon,
    'view-columns': ViewColumnsIcon,
    'viewfinder-circle': ViewfinderCircleIcon,
    'wallet': WalletIcon,
    'wifi': WifiIcon,
    'window': WindowIcon,
    'wrench-screwdriver': WrenchScrewdriverIcon,
    'wrench': WrenchIcon,
    'x-circle': XCircleIcon,
    'x-mark': XMarkIcon
  }
  
  /**
   * Vue composable to get a Heroicon component by its kebab-case name
   * @param {string} iconName - The kebab-case name of the icon
   * @returns {Component|null} The Heroicon component or null if not found
   */
  export function useHeroOutlineIcon(iconName = null) {
    return HeroOutlineIconsMap[iconName ?? 'paper-clip'] || HeroOutlineIconsMap['paper-clip']
  }
  
